In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df_final = pd.read_csv('df_final.csv', index_col='Unnamed: 0')
df_final.sample(10)

MARITALSTATUS       EDUCATION GENDER last_prod_enq2 first_prod_enq2   
1162        Married  UNDER GRADUATE      F             PL              PL  \
20099        Single        GRADUATE      M   ConsumerLoan    ConsumerLoan   
39362       Married        GRADUATE      M         others              PL   
13824        Single        GRADUATE      M   ConsumerLoan          others   
26162        Single            12TH      M   ConsumerLoan          others   
19219       Married            12TH      M             PL              PL   
27186        Single            12TH      M             PL              PL   
28311        Single        GRADUATE      M             PL              AL   
22732       Married        GRADUATE      M         others          others   
43171       Married            12TH      M         others          others   

       pct_tl_open_L6M  pct_tl_closed_L6M  Tot_TL_closed_L12M   
1162             0.000              0.000                   0  \
20099            0.444              0.111                   1   
39362            0.182              0.091                   2   
13824            0.000              0.000                   0   
26162            0.500              0.000                   0   
19219            0.667              0.333                   1   
27186            0.200              0.200                   1   
28311            0.222              0.111                   2   
22732            0.000              0.000                   0   
43171            0.059              0.059                   1   

       pct_tl_closed_L12M  Tot_Missed_Pmnt  ...  NETMONTHLYINCOME   
1162                0.000                0  ...             20000  \
20099               0.111                2  ...             35000   
39362               0.182                0  ...             40000   
13824               0.000                0  ...             20000   
26162               0.000                1  ...             32000   
19219               0.333                0  ...             20000   
27186               0.200                1  ...             50000   
28311               0.222                0  ...             45000   
22732               0.000                0  ...             30000   
43171               0.059                1  ...             33000   

       Time_With_Curr_Empr  pct_of_active_TLs_ever  CC_Flag  PL_Flag   
1162                   126                   0.500        0        0  \
20099                  107                   0.333        0        0   
39362                  185                   0.182        0        0   
13824                   54                   1.000        0        0   
26162                   15                   1.000        0        0   
19219                   77                   0.667        0        1   
27186                   99                   0.400        0        1   
28311                  155                   0.556        0        1   
22732                  150                   1.000        0        0   
43171                  246                   0.294        0        0   

       pct_PL_enq_L6m_of_ever  pct_CC_enq_L6m_of_ever  HL_Flag  GL_Flag   
1162                      0.0                     0.0        0        0  \
20099                     0.0                     0.0        1        0   
39362                     0.5                     0.0        0        0   
13824                     0.0                     0.0        0        0   
26162                     0.0                     0.0        0        0   
19219                     0.5                     0.0        0        0   
27186                     0.0                     0.0        1        0   
28311                     0.0                     0.0        0        0   
22732                     0.0                     0.0        0        0   
43171                     0.0                     0.0        1        0   

       Approved_Flag  
1162              P2  
20099            

In [3]:
X = df_final.drop(columns=['Approved_Flag'])
y = df_final['Approved_Flag']

In [4]:
numerical_cols = []
for cols in X:
    if X[cols].dtype!='object':
        numerical_cols.append(cols)

numerical_cols

['pct_tl_open_L6M',
 'pct_tl_closed_L6M',
 'Tot_TL_closed_L12M',
 'pct_tl_closed_L12M',
 'Tot_Missed_Pmnt',
 'CC_TL',
 'Home_TL',
 'PL_TL',
 'Secured_TL',
 'Unsecured_TL',
 'Other_TL',
 'Age_Oldest_TL',
 'Age_Newest_TL',
 'time_since_recent_payment',
 'max_recent_level_of_deliq',
 'num_deliq_6_12mts',
 'num_times_60p_dpd',
 'num_std_12mts',
 'num_sub',
 'num_sub_6mts',
 'num_sub_12mts',
 'num_dbt',
 'num_dbt_12mts',
 'num_lss',
 'recent_level_of_deliq',
 'CC_enq_L12m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L3m',
 'NETMONTHLYINCOME',
 'Time_With_Curr_Empr',
 'pct_of_active_TLs_ever',
 'CC_Flag',
 'PL_Flag',
 'pct_PL_enq_L6m_of_ever',
 'pct_CC_enq_L6m_of_ever',
 'HL_Flag',
 'GL_Flag']

In [5]:
cat_cols = []
for col in X:
    if X[col].dtype=='object':
        cat_cols.append(col)

cat_cols

['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_train)

(35992, 43)
      MARITALSTATUS       EDUCATION GENDER last_prod_enq2 first_prod_enq2   
34238        Single             SSC      M   ConsumerLoan    ConsumerLoan  \
38632       Married            12TH      M   ConsumerLoan          others   
31466        Single  UNDER GRADUATE      M             PL    ConsumerLoan   
42150       Married        GRADUATE      M         others          others   
21046       Married            12TH      M   ConsumerLoan    ConsumerLoan   
...             ...             ...    ...            ...             ...   
11284        Single             SSC      M             AL              AL   
44732       Married  UNDER GRADUATE      M   ConsumerLoan          others   
38158        Single             SSC      M             HL              CC   
860         Married  UNDER GRADUATE      M   ConsumerLoan    ConsumerLoan   
15795       Married             SSC      M   ConsumerLoan              CC   

       pct_tl_open_L6M  pct_tl_closed_L6M  Tot_TL_closed_L12M  

In [7]:
print(y_train.shape)
print(y_train)

(35992,)
34238    P1
38632    P1
31466    P3
42150    P2
21046    P3
         ..
11284    P2
44732    P2
38158    P2
860      P2
15795    P3
Name: Approved_Flag, Length: 35992, dtype: object


In [8]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

X_train.loc[X_train['EDUCATION'] == 'SSC',['EDUCATION']]              = 1
X_train.loc[X_train['EDUCATION'] == '12TH',['EDUCATION']]             = 2
X_train.loc[X_train['EDUCATION'] == 'GRADUATE',['EDUCATION']]         = 3
X_train.loc[X_train['EDUCATION'] == 'UNDER GRADUATE',['EDUCATION']]   = 3
X_train.loc[X_train['EDUCATION'] == 'POST-GRADUATE',['EDUCATION']]    = 4
X_train.loc[X_train['EDUCATION'] == 'OTHERS',['EDUCATION']]           = 1
X_train.loc[X_train['EDUCATION'] == 'PROFESSIONAL',['EDUCATION']]     = 3

X_test.loc[X_test['EDUCATION'] == 'SSC',['EDUCATION']]              = 1
X_test.loc[X_test['EDUCATION'] == '12TH',['EDUCATION']]             = 2
X_test.loc[X_test['EDUCATION'] == 'GRADUATE',['EDUCATION']]         = 3
X_test.loc[X_test['EDUCATION'] == 'UNDER GRADUATE',['EDUCATION']]   = 3
X_test.loc[X_test['EDUCATION'] == 'POST-GRADUATE',['EDUCATION']]    = 4
X_test.loc[X_test['EDUCATION'] == 'OTHERS',['EDUCATION']]           = 1
X_test.loc[X_test['EDUCATION'] == 'PROFESSIONAL',['EDUCATION']]     = 3


categorical_cols = ['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']

oe = OneHotEncoder(handle_unknown='ignore', drop='first')
X_train_encoded = oe.fit_transform(X_train[categorical_cols])
X_test_encoded = oe.transform(X_test[categorical_cols])

# Convert the sparse matrix to a dense array and assign it to the DataFrame column
X_train_encoded_df = pd.DataFrame(X_train_encoded.toarray(), columns=oe.get_feature_names_out(categorical_cols), index=X_train.index)
X_test_encoded_df = pd.DataFrame(X_test_encoded.toarray(), columns=oe.get_feature_names_out(categorical_cols), index=X_test.index)

# Drop the original 'GENDER' column from the DataFrames
X_train.drop(columns=categorical_cols, inplace=True)
X_test.drop(columns=categorical_cols, inplace=True)

# Concatenate the encoded columns to the original DataFrames
X_train = pd.concat([X_train, X_train_encoded_df], axis=1)
X_test = pd.concat([X_test, X_test_encoded_df], axis=1)


In [9]:
X_train['EDUCATION'].value_counts()

EDUCATION
3    16114
2    10098
1     8191
4     1589
Name: count, dtype: int64

In [10]:
X_test['EDUCATION'].value_counts()

EDUCATION
3    4061
2    2468
1    2048
4     421
Name: count, dtype: int64

In [11]:
X_train.columns

Index(['EDUCATION', 'pct_tl_open_L6M', 'pct_tl_closed_L6M',
       'Tot_TL_closed_L12M', 'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL',
       'Home_TL', 'PL_TL', 'Secured_TL', 'Unsecured_TL', 'Other_TL',
       'Age_Oldest_TL', 'Age_Newest_TL', 'time_since_recent_payment',
       'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'num_times_60p_dpd',
       'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt',
       'num_dbt_12mts', 'num_lss', 'recent_level_of_deliq', 'CC_enq_L12m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'pct_of_active_TLs_ever', 'CC_Flag', 'PL_Flag',
       'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever', 'HL_Flag',
       'GL_Flag', 'MARITALSTATUS_Single', 'GENDER_M', 'last_prod_enq2_CC',
       'last_prod_enq2_ConsumerLoan', 'last_prod_enq2_HL', 'last_prod_enq2_PL',
       'last_prod_enq2_others', 'first_prod_enq2_CC',
       'first_prod_enq2_ConsumerLoan', 'first_prod_enq2

In [12]:
X_train.shape

(35992, 51)

In [13]:
scaler = StandardScaler()

X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])



In [14]:
X_train

EDUCATION  pct_tl_open_L6M  pct_tl_closed_L6M  Tot_TL_closed_L12M   
34238         1         0.184937           1.945866            0.806268  \
38632         2        -0.028611           0.221614            6.103311   
31466         3        -0.649233           4.340660            0.144137   
42150         3        -0.649233          -0.448929           -0.517993   
21046         2        -0.649233           1.945866            0.806268   
...         ...              ...                ...                 ...   
11284         1        -0.649233           0.235983            0.144137   
44732         3        -0.649233          -0.448929           -0.517993   
38158         1        -0.649233          -0.448929           -0.517993   
860           3         2.687446          -0.448929           -0.517993   
15795         1         1.576332          -0.448929           -0.517993   

       pct_tl_closed_L12M  Tot_Missed_Pmnt     CC_TL   Home_TL     PL_TL   
34238            1.342325        -0.510285 -0.260633 -0.211272 -0.347033  \
38632            0.305630         1.321571  5.267178 -0.211272  4.060694   
31466            3.283703        -0.510285 -0.260633 -0.211272 -0.347033   
42150           -0.599052        -0.510285 -0.260633 -0.211272 -0.347033   
21046            3.283703        -0.510285 -0.260633 -0.211272 -0.347033   
...                   ...              ...       ...       ...       ...   
11284           -0.043818         0.405643 -0.260633 -0.211272 -0.347033   
44732           -0.599052        -0.510285 -0.260633 -0.211272 -0.347033   
38158           -0.599052        -0.510285  3.424574 -0.211272  0.754899   
860             -0.599052         0.405643 -0.260633 -0.211272 -0.347033   
15795           -0.599052        -0.510285 -0.260633 -0.211272 -0.347033   

       Secured_TL  ...  last_prod_enq2_CC  last_prod_enq2_ConsumerLoan   
34238   -0.295439  ...                0.0                          1.0  \
38632    0.702834  ...                0.0                          1.0   
31466   -0.461818  ...                0.0                          0.0   
42150   -0.461818  ...                0.0                          0.0   
21046   -0.295439  ...                0.0                          1.0   
...           ...  ...                ...                          ...   
11284    0.702834  ...                0.0                          0.0   
44732   -0.295439  ...                0.0                          1.0   
38158   -0.461818  ...                0.0                          0.0   
860     -0.295439  ...                0.0                          1.0   
15795   -0.129060  ...                0.0                          1.0   

       last_prod_enq2_HL  last_prod_enq2_PL  last_prod_enq2_others   
34238                0.0                0.0                    0.0  \
38632                0.0                0.0                    0.0   
31466                0.0                1.0                    0.0   
42150                0.0                0.0                    1.0   
21046                0.0                0.0                    0.0   
...                  ...                ...                    ...   
11284                0.0                0.0                    0.0   
44732                0.0                0.0                    0.0   
38158                1.0                0.0                    0.0   
860                  0.0                0.0                    0.0   
15795                0.0                0.0                    0.0   

       first_prod_enq2_CC  first_prod_enq2_ConsumerLoan  first_prod_enq2_HL   
34238                 0.0                           1.0                 0.0  \
38632                 0.0                           0.0                 0.0   
31466                 0.0                           1.0                 0.0   
42150                 0.0                           0.0                 0.0   
21046                 0.0                           1.0            

In [18]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)



In [17]:
from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [20]:
lr = LogisticRegression()

lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

print(f"accuracy: {accuracy_score(y_test, y_pred)}")
print("*"*50)
print(f"confusion matrix: {confusion_matrix(y_test, y_pred)}")

accuracy: 0.7507223827517226
**************************************************
confusion matrix: [[ 715  284    3    5]
 [ 119 5063  121   79]
 [  29  953  194  222]
 [   1  282  145  783]]


/Users/aakanksha/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
rf = RandomForestClassifier()

rf.fit(X_train, y_train)
y_pred1 = rf.predict(X_test)

print(f"accuracy: {accuracy_score(y_test, y_pred1)}")
print("*"*50)
print(f"confusion matrix: {confusion_matrix(y_test, y_pred1)}")

accuracy: 0.76661480328962
**************************************************
confusion matrix: [[ 734  273    0    0]
 [ 119 4990  211   62]
 [  30  828  317  223]
 [   2  137  215  857]]


In [19]:
xgb = XGBClassifier()

xgb.fit(X_train, y_train)
y_pred2 = xgb.predict(X_test)

print(f"accuracy: {accuracy_score(y_test, y_pred2)}")
print("*"*50)
print(f"confusion matrix: {confusion_matrix(y_test, y_pred2)}")

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, The experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:EDUCATION: object

In [ ]:
model_name = {
    "RandomForestClassifier": RandomForestClassifier(), 
    "XGBClassifier": XGBClassifier()
}

for model_key, model_value in model_name.items():
    model_value.fit(X_train, y_train)
    y_pred = model_value.predict(X_test)
    print(f"Accuracy for {model_key}: {accuracy_score(y_test, y_pred)}")
    print("*" * 50)
    print(f"Confusion matrix for {model_key}: {confusion_matrix(y_test, y_pred)}")